### ISSUE TITLE
FDSNWS: digest authentication not supported

### ISSUE THREAD

**Issue by megies** [krischer/jane#79] opened 2018-01-24 14:28 UTC
Currently, it is possible to do an authenticated event query by explicitly providing user/password to event queryauth (which is an extension of FDSNWS, kind of) as REST parameters in the url.. e.g.

`http://my_jane/fdsnws/event/1/queryauth?user=myself&password=mypass`

It seems like this is internally handled by picking up user/password and having django do the authentication and permission management during fetching the queryset from the db internally.

But, it is not possible to do such a request using the obspy client, for two reasons:
 - obspy FDSN client is following FDSNWS specs and only goes to ’’queryauth’’ for dataselect queries, as FDSN specs don't say anything about queryauth URL endpoint for event/station service
 - obspy FDSN client does HTTP digest authentication, which Jane does not understand

CC @jwassermann @krischer

**Comment by krischer** [comment] 2018-01-24 14:30
Duplicate of #64.

**Closed by krischer** 2018-01-24 14:30 UTC
Labels: FDSNWS
